using System.Drawing;
using System.Windows.Forms;

namespace CielWin.App.Tray;

/// <summary>
/// Thin WinForms <see cref="NotifyIcon"/>/<see cref="ContextMenuStrip"/> wrapper, the sole owner of
/// the tray icon and its menu. Holds no behavior beyond forwarding clicks to
/// <see cref="TrayMenuController"/>; the rest needs a live notification area and is verified by hand.
/// Constructed on the WPF UI thread, whose dispatcher loop pumps it.
/// </summary>
public sealed class TrayIconHost : IDisposable
{
    private readonly NotifyIcon _icon;
    private readonly Icon? _ownedIcon;
    private readonly ContextMenuStrip _menu;
    private readonly List<Image> _images = [];

    public TrayIconHost(TrayMenuController controller)
    {
        var modeItem = new ToolStripMenuItem("Wallpaper mode") { Image = Track(TrayGlyphs.Render(TrayGlyphs.Mode)) };
        var modeItems = new List<(WallpaperMode Mode, ToolStripMenuItem Item)>();
        foreach (var mode in TrayMenuController.Modes)
        {
            var item = new ToolStripMenuItem(ModeLabel(mode));
            item.Click += (_, _) => controller.SelectMode(mode);
            modeItem.DropDownItems.Add(item);
            modeItems.Add((mode, item));
        }

        var sceneItem = new ToolStripMenuItem("Scene") { Image = Track(TrayGlyphs.Render(TrayGlyphs.Scene)) };
        var sceneItems = new List<(WallpaperScene Scene, ToolStripMenuItem Item)>();
        foreach (var scene in TrayMenuController.Scenes)
        {
            var item = new ToolStripMenuItem(SceneLabel(scene));
            item.Click += (_, _) => controller.SelectScene(scene);
            sceneItem.DropDownItems.Add(item);
            sceneItems.Add((scene, item));
        }

        var exitItem = new ToolStripMenuItem("Exit") { Image = Track(TrayGlyphs.Render(TrayGlyphs.Exit)) };
        exitItem.Click += (_, _) => controller.Exit();

        _menu = new ContextMenuStrip();
        var items = new Dictionary<TrayMenuEntry, ToolStripItem>
        {
            [TrayMenuEntry.Mode] = modeItem,
            [TrayMenuEntry.Scene] = sceneItem,
            [TrayMenuEntry.Exit] = exitItem,
        };
        foreach (var entry in MenuOrder)
        {
            if (entry == TrayMenuEntry.Exit)
            {
                _menu.Items.Add(new ToolStripSeparator());
            }

            _menu.Items.Add(items[entry]);
        }

        // The ticks are re-read on every open, never flipped by WinForms (CheckOnClick stays off):
        // the scene also changes over HTTP, and the controller is the only owner of the state.
        void RefreshChecks()
        {
            foreach (var (mode, item) in modeItems)
            {
                item.Checked = controller.Mode == mode;
            }

            foreach (var (scene, item) in sceneItems)
            {
                item.Checked = controller.Scene == scene;
            }
        }

        RefreshChecks();
        _menu.Opening += (_, _) => RefreshChecks();

        _ownedIcon = LoadTrayIcon();
        _icon = new NotifyIcon
        {
            Icon = _ownedIcon ?? SystemIcons.Application,
            Text = "CielWin",
            ContextMenuStrip = _menu,
            Visible = true,
        };
    }

    /// <summary>
    /// The embedded icon: the Raphael scene's mini figure on a transparent background, generated by
    /// <c>tools/tray-icon/render-raphael-mini.mjs</c> (also the executable's icon).
    /// </summary>
    public const string IconResourceName = "CielWin.App.Assets.raphael-mini.ico";

    /// <summary>The order the items appear in: the mode switch, the scene switch, then exit.</summary>
    public static IReadOnlyList<TrayMenuEntry> MenuOrder { get; } =
    [
        TrayMenuEntry.Mode,
        TrayMenuEntry.Scene,
        TrayMenuEntry.Exit,
    ];

    public static string ModeLabel(WallpaperMode mode) => mode switch
    {
        WallpaperMode.Scene => "Scene wallpaper",
        WallpaperMode.SceneMini => "Mini window",
        _ => mode.ToString(),
    };

    public static string SceneLabel(WallpaperScene scene) => scene.ToString();

    private Image? Track(Image? image)
    {
        if (image is not null)
        {
            _images.Add(image);
        }

        return image;
    }

    /// <summary>
    /// The embedded multi-size icon at the notification area's size, so Windows picks the frame drawn
    /// for this DPI. Null (falls back to the system icon) rather than failing startup.
    /// </summary>
    private static Icon? LoadTrayIcon()
    {
        try
        {
            using var stream = typeof(TrayIconHost).Assembly.GetManifestResourceStream(IconResourceName);
            return stream is null ? null : new Icon(stream, SystemInformation.SmallIconSize);
        }
        catch (Exception exception) when (exception is ArgumentException or System.IO.IOException)
        {
            return null;
        }
    }

    public void Dispose()
    {
        _icon.Visible = false;
        _icon.Dispose();
        // NotifyIcon does not own its Icon and a menu item does not own its Image.
        _ownedIcon?.Dispose();
        _menu.Dispose();
        foreach (var image in _images)
        {
            image.Dispose();
        }
    }
}
